server:
  port: 10011
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # 是否要通过服务中心自动根据 serviceId 创建路由
          lower-case-service-id: false  #是否将服务id转换为小写
      routes:
        - id: provider-service  # 路由的唯一Id
          uri: lb://feign-provider  # 目标服务地址
          predicates:  # 路由条件，接受一个输入参数，返回一个布尔值结果
            - Path=/feign-provider/**
          filters:
            - AddRequestParameter=name, zhangsan
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug