server:
  port: 10011
spring:
  application:
    name: eureka-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka
  instance:
    prefer-ip-address: true  # 以IP地址注册到注册中心