server:
  port: 10012
spring:
  application:
    name: stream-producer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      bindings:
        input:
          destination: steam.message

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka/